version: "3.9"
services:
  shm-codebox-db:
    image: postgres
    restart: always
    container_name: shm-codebox-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
